STOCKS = {
    'Technology': ['MSFT', 'GOOG', 'AMZN', 'AAPL', 'META', 'ORCL', 'NFLX', 'ADBE', 'CRM', 'SAP', 'ACN', 'INTU', 'IBM', 'NOW'],
    'Electronic': ['NVDA', 'TSM', 'AVGO', 'ASML', 'AMD', 'QCOM', 'CSCO', 'TXN', 'ARM', 'INTC', 'HON'],
    'Finance': ['BKR.B', 'JPM', 'BAC', 'WFC', 'AXP', 'BX', 'MS', 'HSBC', 'RY', 'GS'],
    'Health': ['LLY', 'NVO', 'JNJ', 'MKR', 'ABBV', 'AZN', 'NVS', 'TMO', 'DHR', 'AMGN', 'ABT', 'PFE'],
    'Retail_Trade': ['WMT', 'COST', 'HD', 'PDD', 'BABA', 'LOW', 'TJX', 'MELI', 'CVS', 'TGT', 'CRPT', 'ROST',],
    'Consumer_Non-Durables': ['PG', 'KO', 'PEP', 'PN', 'UL', 'BUD', 'NKE', 'MDLZ', 'MO', 'CL', 'BTI', 'DEO',],
    'Energy_Minerals': ['XOM', 'TTE', 'COP', 'BP', 'PBR', 'EQNR', 'CNQ', 'EOG', 'PSX', 'MPC', 'OXY', 'E',],
    'Producer_Manufacturing': ['GE', 'AMAT', 'CAT', 'ETN', 'LRCX', 'DE', 'TT', 'ITW', 'CARP', 'PCAR', 'JCI', 'GEV',],
    'Consumer Services': ['MCD', 'DIS', 'CMCSA', 'BKNG', 'ABNB', 'SPUX', 'CTAS', 'CMG', 'MAR', 'HLT', 'CHTR', 'RCL',],
    # 'Producer_Manufacturing': ['','','','','','','','','','','','',],
    # 'Producer_Manufacturing': ['','','','','','','','','','','','',],
    # 'Producer_Manufacturing': ['','','','','','','','','','','','',],
}
CHANNEL_ID = {'MSFT': 'UCFtEEv80fQVKkD4h1PF-Xqw',
 'GOOG': 'UCK8sQmJBp8GCxrOtXWBpyEA',
 'AMZN': 'UCkLXELm63_pH7L-r-548kig',
 'AAPL': 'UCE_M8A5yxnLfW0KghEeajjw',
 'META': 'UC04FyDIvYXNecpbG8gyOw4A',
 'ORCL': 'UCHCThmyZ-2yWkv0UVeBDdnQ',
 'NFLX': 'UCWOA1ZGywLbqmigxE4Qlvuw',
 'ADBE': 'UC5_SBQbLA9Kg7Jh5GpXoP3g',
 'CRM': 'UCUpquzY878NEaZm5bc7m2sQ',
 'SAP': 'UCVnIv2xF2wyMMCSKv1qF3pA',
 'ACN': 'UCvDOfCgmS7q4OYMKVpy5Xjw',
 'INTU': 'UC-Q8p3gbbRDxskIEf0LNYVA',
 'IBM': 'UC8cc4pVKVHG7A9fbNsRNrLQ',
 'NOW': 'UCLukrOQYSgsHUR_NSiVZndQ',
 'NVDA': 'UCHuiy8bXnmK5nisYHUd1J5g',
 'TSM': 'UC02yNxGj2MxhynehcWSxcLg',
 'AVGO': 'UCTr3zah69bISSVdBcHiKhpA',
 'ASML': 'UCxP5I5E0rTkBm71Mwn6lm0g',
 'AMD': 'UChw9eQC9trZ13SLDQf3HDbg',
 'QCOM': 'UCH6eZr6vbZ6Bx53TyuSzxrg',
 'CSCO': 'UCEWiIE6Htd8mvlOR6YQez1g',
 'TXN': 'UC-77g3ZfbmoiUJH4ABsM-LQ',
 'ARM': 'UCvcBJFXTzCfU_sILnYVd4gg',
 'INTC': 'UCk7SjrXVXAj8m8BLgzh6dGA',
 'HON': 'UC-kFH2fpyttdWAWmJLqT7aQ',
 'JPM': 'UCBnFes2U2diA3QfR5m8l_Tw',
 'BAC': 'UCtHZ1qs5h4sx9TijVBQCMIA',
 'WFC': 'UCGcBOP3IhbgHOPBcUFUZRdQ',
 'AXP': 'UCYul_HOJB7MeEb0ucJCtmDg',
 'BX': 'UCWP3K_Lfy7yc5J2Wa50RWHA',
 'MS': 'UCkIWVCDGpy9gyPwev6yllYw',
 'HSBC': 'UCTbuSzdKMgyVRjlr1EWE-gg',
 'RY': 'UCGXGTJt7GOgX0fyj2OPq1JQ',
 'GS': 'UCyz6-taovlaOkPsPtK4KNEg',
 'LLY': 'UCo4mvtNK1kKZVVE8s_UCAnA',
 'NVO': 'UCIKYEgdvpEHwYo6HfNNDrRg',
 'JNJ': 'UCg0sL-UssDXE2Ohk3Dfpz7g',
 'ABBV': 'UCDT-v557CdMg5n7bg2OAcjA',
 'AZN': 'UCMgYWrwBkhUxGyRwdsrVHIg',
 'NVS': 'UCSg28bDoEVjVegY4-htQM7A',
 'TMO': 'UCfUs2fCDhx07fkszsJ0jOcA',
 'DHR': 'UCe7s1LMEO8Gh6cEEGKQQbDw',
 'AMGN': 'UCDCWgYMRqAQL8uqghy328-g',
 'ABT': 'UC346EX3v26ACsjLhe-HwHDg',
 'PFE': 'UCzoP7l5bzSzi2gUUNn0I79w',
 'WMT': 'UC701pqb1-HJPS4RMjSmK4Yg',
 'COST': 'UCB-tgpOz-2qx6qe6-ADVBGw',
 'HD': 'UCbkgNEbfRBOl6m2IyUk9K7w',
 'PDD': 'UCrxIGfBCKvigmreaxaiU6Tg',
 'BABA': 'UCJ9fkHpENAdCJ7HlIgDL7Vg',
 'LOW': 'UCqd2hbtE2N9fb0D2nTrLT1w',
 'TJX': 'UCJU1VGF9g4tOwrWYyGFKfcw',
 'MELI': 'UCfGKZnz6LPQNm-F0nlWjGzQ',
 'CVS': 'UChickNdPOc6P_JE3MbPsDNQ',
 'TGT': 'UCralvBh1hSGRf4SrjS-mY7Q',
 'CRPT': 'UCB5QCmwNrEkqJ-iMzuZs4jA',
 'ROST': 'UCqUsOMSpzLvLXLgWe8RKYgw',
 'PG': 'UCDzq6J0KoGCbps96JQuXWRg',
 'KO': 'UCosXctaTYxN4YPIvI5Fpcrw',
 'PEP': 'UCkrcntqtKKsXHBNJ5yvdQzg',
 'UL': 'UCMVcaTH8mk0POzGBvjWa7tg',
 'BUD': 'UCLhfF--SfZ7ExtoNDDMPx0w',
 'NKE': 'UCUFgkRb0ZHc4Rpq15VRCICA',
 'MDLZ': 'UC4K4zLoKvkhNhgRTctZu8JA',
 'MO': 'UCvtoUspjvQxW01JbvRhxtIg',
 'CL': 'UCA-uIKLCzTJSI1HdGyfmsDQ',
 'BTI': 'UCRhTI2YTCkW-6gDqxqU1xyQ',
 'DEO': 'UC1NS0GtKPDOjc7vFrNBkoOQ',
 'XOM': 'UCvNc3rg1Aa9wSPECYWEfcPg',
 'TTE': 'UCXc0jPCckEICHgJlW-HKsRQ',
 'COP': 'UCp5AyTHS1_N-KTMTYjicqlg',
 'BP': 'UC9m-Yl4kfv8nIriI7Ry8CxA',
 'PBR': 'UCWMy2SX8DFyTcwcvzu4UeMQ',
 'EQNR': 'UCwyLglaZ7FUVAIZTBYvgC8w',
 'CNQ': 'UConlnbEJ_fbp083MCujVkWQ',
 'EOG': 'UCV2XNK2luIuVNg6nPJvpkLw',
 'PSX': 'UCfVsCtw47CXDDjCu8_l50ww',
 'MPC': 'UCBmSUnqAGPy2FXii-bmTctg',
 'OXY': 'UCCR-kIn1ImswuunjuDhL2RA',
 'E': 'UC744cdZc47ts2zGBmypoyqA',
 'GE': 'UCsoB6O14wNa8-7dHMfxftgA',
 'AMAT': 'UCRtDxSpmTncPvzBvXLurThA',
 'CAT': 'UCpl50Ni3pjZIaZCETZA8fjg',
 'ETN': 'UCF7vz2IAPNHv7BKTiFC9Xhw',
 'LRCX': 'UCYIzu7SOyUyDPwMgUSspRYw',
 'DE': 'UC2L3aOMv5mAA_IEbiey7Nrg',
 'TT': 'UC1QY4zka5T9aEgrlpvUqG9Q',
 'ITW': 'UCJEy66c7FzfU-M0-3_xFq7Q',
 'PCAR': 'UCzuHQhMg4CZAt6XycBYja6g',
 'JCI': 'UCVdxOo2SYGefzEFMVVkPgkQ',
 'GEV': 'UC6yKylYBunWCgqY4s-mqZCg',
 'MCD': 'UCRI5ZedBs0_BYY4PlxD6m7w',
 'DIS': 'UCHNff2hWPZKlj5gAza-UN8g',
 'CMCSA': 'UC_Skz24vMgLpm6sdLSoETEA',
 'BKNG': 'UCde5lyhz54IYdyrbGA5F5rg',
 'ABNB': 'UCCww-R0oM_CQWXerBcNyKKw',
 'CTAS': 'UCBsX3LG76zuKA2RZp8BJKGA',
 'CMG': 'UClrnM-TRoxc-Mv48wgkukrg',
 'MAR': 'UC79084aTJ78NAbF7tOvA8hg',
 'HLT': 'UCStzHveCf_orXJ-19kiOUog',
 'CHTR': 'UCqx-k-wcqulofG_NEReJWvQ',
 'RCL': 'UCGXGTJt7GOgX0fyj2OPq1JQ'}
